/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgSelectState.java
 *
 * Created on Feb 16, 2012, 10:24:14 PM
 */
package pk.com.rsoft.classcontractstestbed;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultListModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import pk.com.rsoft.classcontractstestbed.util.graph.State;
import pk.com.rsoft.classcontractstestbed.util.graph.Transition;
import pk.com.rsoft.classcontractstestbed.util.inequality.InEqualitySimplified;

import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JLabel;

/**
 *
 * @author HAMMAD
 */
public class DlgSelectState extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private ArrayList<State> lstStates;
    /** Creates new form DlgSelectState */
    public DlgSelectState(DrawingPane parent, boolean modal,ArrayList<State> lstState) {
        super(parent, modal);
        setTitle("Edit States");

        initComponents();
        this.lstStates = lstState;   
        if(lstState!=null)
        {
            loadStates(lstState);
        }
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pk.com.rsoft.classcontractstestbed.ClassContractsTestbedApp.class).getContext().getResourceMap(DlgSelectState.class);
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select a State:"); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        
        textField = new JTextField();
        textField.setColumns(10);
        
        JButton btnNewButton = new JButton("Update");
        jListStates = new javax.swing.JList();
        jListStates.addListSelectionListener(new ListSelectionListener() {
        	public void valueChanged(ListSelectionEvent arg0) {
        		State st = getState(jListStates.getSelectedValue().toString(),lstStates);
        		if(st==null)
        		{
        			System.out.println("State is null!");
        		}
        		else
        		{
            		DlgSelectState.this.loadTransitions(st);        			
        		}

        	}
			private State getState(String string, ArrayList<State> lstStates) {
				// TODO Auto-generated method stub
				for(State st:lstStates)
				{
					if(st.toString().equals(string))
					{
						return st;
					}
				}
				return null;
			}
        });
        
                jListStates.setName("lstSt");
        
        jListVariables = new JList();
        jListVariables.addListSelectionListener(new ListSelectionListener() {
        	public void valueChanged(ListSelectionEvent arg0) {
        		InEqualitySimplified inq = (InEqualitySimplified) jListVariables.getSelectedValue();
        	DlgSelectState.this.textField.setText(inq.getVariable().getValue());
        	DlgSelectState.this.lblVar.setText(inq.getVariableName()+ " " +inq.getType());
        	}
        });
        jListVariables.setName("jListVars");
        
        lblVar = new JLabel("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(okButton, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(cancelButton))
        						.addComponent(jListStates, GroupLayout.PREFERRED_SIZE, 453, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblVar)
        					.addGap(47)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(textField, 256, 256, 256)
        				.addComponent(btnNewButton)
        				.addComponent(jListVariables, GroupLayout.PREFERRED_SIZE, 418, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblVar))
        			.addGap(5)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(btnNewButton))
        			.addGap(11)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jListStates, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jListVariables, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
        			.addGap(8)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(okButton)
        				.addComponent(cancelButton))
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {okButton, cancelButton});
        getContentPane().setLayout(layout);

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
private void loadStates(ArrayList<State> lst)        
{
    DefaultListModel model = new DefaultListModel();
    for(State st: lst)
    {
    	model.addElement(st);    	
//        model.addElement(st.getStrName());
    }
    this.jListStates.setModel(model);
}
private void loadVariables(State st)
{
	DefaultListModel model = new DefaultListModel();
//	System.out.println(st.toString());
	for(InEqualitySimplified inq: st.getCurrentValues())
	{
		model.addElement(inq);		
//		model.addElement(inq.toString());

	}
	this.jListVariables.setModel(model);
}



private void loadTransitions(State st)
{
	DefaultListModel model = new DefaultListModel();
//	System.out.println(st.toString());
	for(Transition trans: st.getArNextStates())
	{
		model.addElement(trans);		
//		model.addElement(inq.toString());

	}
	this.jListVariables.setModel(model);
}




    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                DlgSelectState dialog = new DlgSelectState(null, true,null);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListStates;
    private javax.swing.JButton okButton;
    private JLabel lblVar;    
    private JList jListVariables;    
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
    private JTextField textField;
}
